FROM quay.io/keycloak/keycloak:19.0.3
EXPOSE 8080

ENV KEYCLOAK_USER=admin
ENV KEYCLOAK_PASSWORD=admin
ENV KEYCLOAK_IMPORT=/tmp/keycloak-ees-realm.json 

COPY ./keycloak-ees-realm.json /tmp/keycloak-ees-realm.json